server:
  port: 9002
  shutdown: graceful
  netty:
    idle-timeout: 15s
    connection-timeout: 2s
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ucup_order
    username: user
    password: password
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/ucup_order
  output:
    ansi:
      enabled: always
ucup:
  catalog-service-uri: "http://localhost:9001/"