CREATE TABLE orders
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_isbn          varchar(255)                            NOT NULL,
    book_name          varchar(255),
    book_price         DOUBLE PRECISION,
    quantity           int                                     NOT NULL,
    status             varchar(255)                            NOT NULL,
    created_date       timestamp                               NOT NULL,
    last_modified_date timestamp                               NOT NULL,
    version            integer                                 NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
)


